# Generated by Django 5.2 on 2025-04-24 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='last_searched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
